### ISSUE TITLE
Throws 400 error, Not working, 

### ISSUE THREAD

**Issue by sparsh-git-dev** [Yoda-Man/aws_s3_upload_lite#2]

**Comment by Yoda-Man** [comment]
Hi My apologies for the delay I will take a look this weekend I have been supper busy.

**Comment by rsaf** [comment]
This error is still happening. I just tried today with `aws_s3_upload_lite: ^0.1.3`.

Any fix?

**Comment by Yoda-Man** [comment]
Sometimes its a Bucket policy sometimes its a CORS policy. 
have a look at some samples.

Bucket Policy
   {
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "AllowPublicRead",
            "Effect": "Allow",
            "Principal": {
                "AWS": "*"
            },
            "Action": "s3:*",
            "Resource": "arn:aws:s3:::bucketname/*"
        }
    ]
}


CORS Policy

[
    {
        "AllowedHeaders": [
            "*"
        ],
        "AllowedMethods": [
            "GET",
            "PUT",
            "POST"
        ],
        "AllowedOrigins": [
            "*"
        ],
        "ExposeHeaders": []
    },
    {
        "AllowedHeaders": [
            "*"
        ],
        "AllowedMethods": [
            "PUT",
            "POST",
            "DELETE",
            "GET",
            "HEAD"
        ],
        "AllowedOrigins": [
            "*",
            "https://yourwebsite.com" //Optional
        ],
        "ExposeHeaders": []
    }
]

**Comment by rajpalanand** [comment]
I have my bucket policy and CORS policy exactly as you described still getting 400

**Comment by Yoda-Man** [comment]
Hi I added a new method with upload progress option. could you please try that.

**Comment by rajpalanand** [comment]
Hey Yoda,
I added some debug statements in aws_s3_upload_lite file and figured out that I was getting an AWS ACL error while uploading, fixed that error and it worked perfectly 😄 
Thanks for the package and support!
